### ISSUE TITLE
Is there a way to run homogeneous graphs?

### ISSUE THREAD

**Issue by boxorange** [KiddoZhu/NBFNet-PyG#4]
Hi,

Unlike the NBFNet based on TorchDrug, I don't see codes and configs for homogeneous graphs in the PyG version. Is there a way to run homogeneous graphs on the PyG version?

Thanks in advance.

**Comment by KiddoZhu** [comment]
Hi! Sorry, the PyG version doesn't contain implementation for homogenous graphs.

**Comment by boxorange** [comment]
I see. Thanks for the answer. I think I can use the NBFNet TorchDrug version for my homogeneous graphs instead.
