### ISSUE TITLE
Why can't I reproduce the results?

### ISSUE THREAD

**Issue by moguizhizi** [KiddoZhu/NBFNet-PyG#6]
![1667778233352](https://user-images.githubusercontent.com/53420703/200201991-d5df57f2-98c9-45f6-a0d3-5a919bf40fb9.png)
![1667778309939](https://user-images.githubusercontent.com/53420703/200202057-b45b0289-a0c6-4310-b541-ac4e1c2a0a07.png)
![1667778347321](https://user-images.githubusercontent.com/53420703/200202083-b58187bd-576a-418f-915e-a3b613c84ec9.png)
![1667778381438](https://user-images.githubusercontent.com/53420703/200202103-e5341410-2dec-4fab-bc19-3c413541de1f.png)

**Comment by KiddoZhu** [comment]
Hi! Please look at the HITS@10_50 metric. Actually you reproduced the results.

**Comment by moguizhizi** [comment]
Thank you！
